export const FETCH_CODE = "FETCH_CODE";
export const FETCH_NAME = "FETCH_NAME";
export const FETCH_ID = "FETCH_ID";
export const FETCH_ONEXCHANGE_INDIVIDUAL = "FETCH_ONEXCHANGE_INDIVIDUAL";
export const FETCH_OFFEXCHANGE_INDIVIDUAL = "FETCH_OFFEXCHANGE_INDIVIDUAL";
export const FETCH_OFFEXCHANGE_GROUP = "FETCH_OFFEXCHANGE_GROUP";
export const FETCH_ONEXCHANGE_GROUP = "FETCH_ONEXCHANGE_GROUP";
